import { Inter_Tight, Onest } from 'next/font/google'
import './globals.css';
import Header from './components/header/Header';

const nunito = Onest({ subsets: ['latin'] })

export const metadata = {
  title: 'Luis | Personal Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div style={{ textAlign: 'center', margin: '20px 0' }}>
        <button id="pdfButton" style={{ padding: '10px 20px', fontSize: '16px', cursor: 'pointer' }}>
          Descargar Página Completa en PDF
        </button>
      </div>
        <Header />
        {children}</body>
    </html>
  )
}
